name: Task 3. API Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Code
        uses: actions/checkout@v4

      - name: Checkout API Service
        uses: actions/checkout@v4
        with:
          repository: bondarenkokate73/simbirsoft_sdet_project
          path: api-service

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Start API Service with Docker Compose
        run: |
          cd api-service
          docker compose up --build -d

      - name: Install netcat
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat

      - name: Wait for API service
        run: |
          timeout 120s bash -c '
            until docker ps --filter "name=postgres" --format "{{.Status}}" | grep -q "healthy"; do
              sleep 10;
            done
          '
          timeout 120s bash -c '
            while ! nc -z localhost 8080; do 
              sleep 10;
            done
          '
          sleep 20

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run API tests
        run: |
          cd main
          mvn clean test -Dsurefire.suiteXmlFiles=testng.xml

      - name: Generate Allure report
        run: |
          cd main
          mvn allure:report
        if: always()

      - name: Publish Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: main/target/allure-results
          gh_pages: gh-pages

      - name: Stop API Service
        if: always()
        run: |
          cd api-service
          docker compose down