name: Task 3. API Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "Task-3" ]

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run API tests
        run: |
          cd main
          mvn clean test -Dsurefire.suiteXmlFiles=testng.xml

      - name: Generate Allure report
        run: |
          cd main
          mvn allure:report

      - name: Publish Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: main/target/allure-results
          gh_pages: gh-pages

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: main/target/allure-results/